### ISSUE TITLE
Compute isopycnal overturning from z level output

### ISSUE THREAD

**Issue by jetesdal** [raphaeldussin/xoverturning#11]
Very nice work! I would love to use this package for my analysis. I am looking for a way to compute the overturning in density space, but I only have z level data (`ocean_annual_z`). I see an example for density coordinates `rho2`. Is there a way to use the tool to get the isopycnal overturning (let's say in `sigma1`) from z level output?

To illustrate what my goal is, I am attaching a figure from [Newsom et al. (2016)](http://journals.ametsoc.org/doi/10.1175/JCLI-D-15-0513.1). Here they present the isopycnal overturning in the Southern Hemisphere remapped to depth coordinates (panels A-F).
![Screen Shot 2021-05-11 at 9 32 44 PM](https://user-images.githubusercontent.com/8991018/117951343-5f07da00-b314-11eb-8877-eb4da17d0bac.png)

Currently, I can get the overturning in depth-level coordinates with
`moc = calcmoc(ds, dsgrid=grid)`

And the output is equivalent to what is shown in panels G and H of the Newsom Figure 5 above:
![Screen Shot 2021-05-12 at 11 26 54 AM](https://user-images.githubusercontent.com/8991018/117951948-f5d49680-b314-11eb-9d8b-9d2587400a7d.png)

However, I would like to get something as shown in panel A and B in the Newsom Figure. I think I can do this with [xgcm transform](https://xgcm.readthedocs.io/en/latest/transform.html), but I wanted to check if this might already be implemented in xoverturning.

**Comment by raphaeldussin** [comment]
Thanks Jan-Erik! Glad the tool works for you!
I don't have a z -> sigma transformation built-in since xoverturning should be able to accept any vertical axis.
I think xgcm is the way to go but some may argue that to do the computation properly you need the output in density space.

**Comment by jetesdal** [comment]
Hi @raphaeldussin! Thanks for clarifying. 

I've been working on an [example](https://gist.github.com/jetesdal/dd8df57b643eee0f7cde5badc5a6f002) using xgcm. It uses the same sample data as in [Computing Meridional Overturning](https://mom6-analysiscookbook.readthedocs.io/en/latest/notebooks/Overturning.html). This might be out of scope for xoverturning (so feel free to close the issue), but maybe it would be interesting to include in [MOM6-AnalysisCookbook](https://github.com/raphaeldussin/MOM6-AnalysisCookbook)?

Would it be useful to compare the results from `ocean_annual_rho2` in [Overturning.ipynb](https://mom6-analysiscookbook.readthedocs.io/en/latest/notebooks/Overturning.html#Density-coordinates) with my approach?

I assume Graeme (@gmacgilchrist) also has some insight and could comment on the validity of my current approach.

**Comment by raphaeldussin** [comment]
@jetesdal I think your analysis would be a great addition to the cookbook. We have runs with both rho2 and z output so you could make a comparison of both methods so we can estimate potential differences. Will close it here and please open a PR to the cookbook when you're ready. If you don't have access to data behind the firewall, write the analysis without running cells and I can run them for you.

**Comment by gmacgilchrist** [comment]
@jetesdal This looks great, and I think what you're doing is as good as we can do with offline data. Adding this to the cookbook would be great indeed, and likewise comparing this offline calculation with an online rho2 coordinate overturning would be valuable. I expect we have output for that in the runs that you're looking at.
